import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from quantbench.agent.llm import LLMClient
from quantbench.agent.prompts import SYSTEM_PROMPT
from quantbench.artifact.store import ArtifactStore
from quantbench.config import DEFAULT_COST_BPS, DEFAULT_MODEL, MAX_STEPS, RUNS_DIR
from quantbench.data.cache import file_sha256
from quantbench.data.exchange import SYNTHETIC_FALLBACK_SOURCE, fetch_ohlcv
from quantbench.data.universe import UniverseDefinition, build_universe
from quantbench.data.warehouse import fetch_universe_ohlcv
from quantbench.engine.cross_sectional_backtest import run_cross_sectional_backtest
from quantbench.engine.metrics import sanity_check_metrics
from quantbench.engine.vectorized_backtest import run_vectorized_backtest
from quantbench.skills.codeexec import load_signal_function, run_signal_code
from quantbench.skills.data_quality import DataQualityReport, validate_universe_data
from quantbench.skills.plot import save_drawdown_plot, save_equity_curve_plot, save_group_returns_plot, save_ic_plot
from quantbench.skills.registry import Skill, SkillRegistry
from quantbench.skills.report import build_cross_sectional_research_note, build_research_note


@dataclass
class RunResult:
    run_id: str
    run_dir: Path
    metrics: dict[str, float]
    warnings: list[str]
    summary: str


FETCH_OHLCV_PARAMS = {
    "type": "object",
    "properties": {
        "symbol": {"type": "string", "description": "e.g. BTC/USDT for crypto, AAPL/MSFT/SPY for US equities"},
        "timeframe": {"type": "string", "description": "e.g. 4h for crypto, 1d for equities"},
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
    },
    "required": ["symbol", "timeframe", "start", "end"],
}

SIGNAL_FILE_HEADER = '''"""QuantBench Phase 0 signal - generated by the Coordinator agent.

Runnable standalone: `python signal.py <data.parquet> [--output out.csv]`
"""
import numpy as np
import pandas as pd


'''

SIGNAL_FILE_HARNESS = '''

if __name__ == "__main__":
    import argparse
    import os
    import sys
    from contextlib import contextmanager

    sys.dont_write_bytecode = True
    parser = argparse.ArgumentParser()
    parser.add_argument("data_path")
    parser.add_argument("--output")
    args = parser.parse_args()

    @contextmanager
    def _suppress_native_stderr():
        stderr_fd = 2
        saved_fd = os.dup(stderr_fd)
        try:
            with open(os.devnull, "w") as devnull:
                os.dup2(devnull.fileno(), stderr_fd)
                yield
        finally:
            os.dup2(saved_fd, stderr_fd)
            os.close(saved_fd)

    with _suppress_native_stderr():
        _df = pd.read_parquet(args.data_path)

    if "symbol" in _df.columns:
        # Multi-symbol panel (Phase 1 cross-sectional runs). compute() must be
        # applied per symbol, in the exact same shape run_cross_sectional_backtest
        # uses internally - never across the mixed long table directly, or the
        # reproduced numbers will silently diverge from the real backtest.
        _frames = []
        for _symbol, _symbol_df in _df.groupby("symbol", sort=False):
            _symbol_df = _symbol_df.sort_values("timestamp").reset_index(drop=True)
            _out_symbol = _symbol_df[["timestamp"]].copy()
            _out_symbol["symbol"] = _symbol
            _out_symbol["signal"] = compute(_symbol_df)
            _frames.append(_out_symbol)
        _out = pd.concat(_frames, ignore_index=True).sort_values(["timestamp", "symbol"])
    else:
        _out = _df[["timestamp"]].copy()
        _out["signal"] = compute(_df)

    _csv = _out.to_csv(index=False)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(_csv)
    else:
        print(_csv)
'''

RUN_SIGNAL_BACKTEST_PARAMS = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Python source defining `def compute(df: pd.DataFrame) -> pd.Series`. "
                "Only `pd` and `np` are available, no imports. Must be causal: only use "
                "rows up to and including the current index, never future rows."
            ),
        },
        "cost_bps": {
            "type": "number",
            "description": "Round-trip trading cost in basis points. Default 5.",
        },
    },
    "required": ["code"],
}

BUILD_UNIVERSE_PARAMS = {
    "type": "object",
    "properties": {
        "universe_name": {"type": "string", "description": "Universe name, currently sp500."},
        "as_of_date": {"type": "string", "description": "YYYY-MM-DD date for the universe definition."},
        "point_in_time": {
            "type": "boolean",
            "description": "Phase 1 v1 only supports false. True raises an explicit not-implemented error.",
        },
        "limit": {
            "type": "integer",
            "description": (
                "Optional: truncate to the first N tickers (alphabetically) instead of the "
                "full ~500. Use this whenever the user asks for a quick/small/cheap test - "
                "fetching all 500 symbols sequentially is slow and not needed to sanity-check "
                "a factor idea. The universe is clearly marked as a non-representative sample."
            ),
        },
    },
    "required": ["universe_name", "as_of_date"],
}

RUN_CROSS_SECTIONAL_BACKTEST_PARAMS = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Python source defining `def compute(df: pd.DataFrame) -> pd.Series`. "
                "The function is called once per symbol and must be causal."
            ),
        },
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
        "timeframe": {"type": "string", "description": "Use 1d for US equities."},
        "n_groups": {"type": "integer", "description": "Number of factor groups, default 10."},
        "cost_bps": {"type": "number", "description": "Round-trip trading cost in basis points. Default 5."},
    },
    "required": ["code", "start", "end"],
}


class _RunContext:
    """Mutable state threaded through one Coordinator.run() call."""

    def __init__(self) -> None:
        self.data_path: Path | None = None
        self.data_df = None
        self.cache_meta: dict[str, Any] | None = None
        self.last_metrics: dict[str, float] | None = None
        self.signal_code: str | None = None
        self.universe: UniverseDefinition | None = None
        self.panel_df = None
        self.data_quality: DataQualityReport | None = None
        self.cross_sectional = False
        self.warnings: list[str] = []


def _build_registry(ctx: _RunContext, run) -> SkillRegistry:
    registry = SkillRegistry()

    def _fetch_ohlcv(symbol: str, timeframe: str, start: str, end: str) -> dict:
        data_path, data_df, cache_meta = fetch_ohlcv(symbol, timeframe, start, end)
        ctx.data_path, ctx.data_df, ctx.cache_meta = data_path, data_df, cache_meta

        if cache_meta.get("source") == SYNTHETIC_FALLBACK_SOURCE:
            ctx.warnings.append(
                "DATA IS SYNTHETIC, NOT REAL MARKET DATA. Real data fetch failed "
                f"({cache_meta.get('fallback_reason')}); every downstream metric is "
                "meaningless for real trading decisions."
            )
        elif cache_meta.get("source") == "unknown_legacy_cache":
            ctx.warnings.append(
                "Cached data has no provenance metadata (cached before source tracking "
                "existed). Delete data_cache/ and re-run to confirm real vs synthetic."
            )

        return {
            "rows": len(data_df),
            "start": str(data_df["timestamp"].iloc[0]) if len(data_df) else None,
            "end": str(data_df["timestamp"].iloc[-1]) if len(data_df) else None,
            "source": cache_meta.get("source"),
            "cache_hit": cache_meta.get("cache_hit"),
        }

    def _run_signal_backtest(code: str, cost_bps: float = DEFAULT_COST_BPS) -> dict:
        if ctx.data_df is None:
            return {"error": "no market data loaded yet - call fetch_ohlcv first"}

        signal = run_signal_code(code, ctx.data_df)
        backtest = run_vectorized_backtest(ctx.data_df, signal, cost_bps=cost_bps)

        ctx.signal_code = code
        ctx.last_metrics = backtest.metrics
        run.save_code("signal.py", SIGNAL_FILE_HEADER + code + SIGNAL_FILE_HARNESS)
        run.save_json("backtest_result.json", backtest.to_json_dict())
        save_equity_curve_plot(backtest.equity_curve, run.run_dir / "equity_curve.png")
        save_drawdown_plot(backtest.drawdown, run.run_dir / "drawdown.png")

        new_warnings = sanity_check_metrics(backtest.metrics)
        ctx.warnings.extend(new_warnings)

        return {**backtest.metrics, "warnings": new_warnings}

    def _build_universe(
        universe_name: str, as_of_date: str, point_in_time: bool = False, limit: int | None = None
    ) -> dict:
        universe = build_universe(universe_name, as_of_date, point_in_time=point_in_time, limit=limit)
        ctx.universe = universe
        run.save_text("universe.yaml", __import__("yaml").safe_dump(universe.to_dict(), sort_keys=False, allow_unicode=True))
        ctx.warnings.append(universe.survivorship_bias_note)
        return {
            "name": universe.name,
            "as_of_date": universe.as_of_date,
            "symbols": len(universe.symbols),
            "point_in_time": universe.point_in_time,
            "sample_limit": universe.sample_limit,
            "survivorship_bias_note": universe.survivorship_bias_note,
            "source": universe.source,
        }

    def _run_cross_sectional_backtest(
        code: str,
        start: str,
        end: str,
        timeframe: str = "1d",
        n_groups: int = 10,
        cost_bps: float = DEFAULT_COST_BPS,
    ) -> dict:
        if ctx.universe is None:
            return {"error": "no universe loaded yet - call build_universe first"}

        panel, cache_meta = fetch_universe_ohlcv(ctx.universe, timeframe, start, end)
        ctx.panel_df = panel
        ctx.cache_meta = cache_meta
        ctx.data_quality = validate_universe_data(panel, ctx.universe, end=end)
        ctx.cross_sectional = True

        if ctx.data_quality.symbols_missing_entirely:
            ctx.warnings.append(
                f"{len(ctx.data_quality.symbols_missing_entirely)} universe symbols have no data and were excluded."
            )
        if ctx.data_quality.symbols_with_gaps:
            ctx.warnings.append(f"{len(ctx.data_quality.symbols_with_gaps)} symbols have missing business-day gaps.")
        if ctx.data_quality.suspicious_price_jumps:
            ctx.warnings.append(
                f"{len(ctx.data_quality.suspicious_price_jumps)} symbols have >50% one-period price jumps."
            )

        compute = load_signal_function(code)
        backtest = run_cross_sectional_backtest(
            panel,
            compute,
            n_groups=n_groups,
            cost_bps=cost_bps,
        )

        ctx.signal_code = code
        ctx.last_metrics = backtest.metrics
        panel_path = run.run_dir / "panel.parquet"
        panel.to_parquet(panel_path, index=False)
        run.save_code("signal.py", SIGNAL_FILE_HEADER + code + SIGNAL_FILE_HARNESS)
        run.save_json("cross_sectional_backtest_result.json", backtest.to_json_dict())
        run.save_json("data_quality_report.json", ctx.data_quality.to_dict())
        save_equity_curve_plot(backtest.equity_curve, run.run_dir / "equity_curve.png")
        save_drawdown_plot(backtest.drawdown, run.run_dir / "drawdown.png")
        save_group_returns_plot(backtest.group_returns, run.run_dir / "group_returns.png")
        save_ic_plot(backtest.ic_series, run.run_dir / "rank_ic.png")

        new_warnings = sanity_check_metrics(backtest.metrics)
        ctx.warnings.extend(new_warnings)

        return {
            **backtest.metrics,
            "data_quality": ctx.data_quality.to_dict(),
            "cache": cache_meta,
            "warnings": new_warnings,
        }

    registry.register(
        Skill("fetch_ohlcv", "Fetch and cache OHLCV market data.", FETCH_OHLCV_PARAMS, _fetch_ohlcv)
    )
    registry.register(
        Skill(
            "run_signal_backtest",
            "Run signal code against the fetched data and backtest it.",
            RUN_SIGNAL_BACKTEST_PARAMS,
            _run_signal_backtest,
        )
    )
    registry.register(
        Skill("build_universe", "Build a named equity universe such as the current S&P 500.", BUILD_UNIVERSE_PARAMS, _build_universe)
    )
    registry.register(
        Skill(
            "run_cross_sectional_backtest",
            "Fetch a universe panel, run causal factor code per symbol, and backtest equal-weight factor groups.",
            RUN_CROSS_SECTIONAL_BACKTEST_PARAMS,
            _run_cross_sectional_backtest,
        )
    )
    return registry


def _message_to_dict(message: Any) -> dict:
    entry: dict[str, Any] = {"role": getattr(message, "role", "assistant"), "content": getattr(message, "content", None)}
    tool_calls = getattr(message, "tool_calls", None)
    if tool_calls:
        entry["tool_calls"] = [
            {
                "id": call.id,
                "type": "function",
                "function": {"name": call.function.name, "arguments": call.function.arguments},
            }
            for call in tool_calls
        ]
    return entry


class Coordinator:
    def __init__(
        self,
        model: str | None = None,
        run_store: ArtifactStore | None = None,
        llm: LLMClient | None = None,
    ):
        self.model = model or DEFAULT_MODEL
        self.run_store = run_store or ArtifactStore(RUNS_DIR)
        self.llm = llm or LLMClient(self.model)

    def run(self, user_request: str) -> RunResult:
        run = self.run_store.create_run(user_request)
        return self.execute(run, user_request)

    def execute(self, run, user_request: str) -> RunResult:
        """Drive the tool-use loop for an already-created Run.

        Split out from `run()` so callers that need the run_id before execution
        finishes (e.g. the web API, which returns run_id immediately and runs
        the loop in a background thread) can call `run_store.create_run(...)`
        themselves first, then hand the Run object here.
        """
        ctx = _RunContext()
        registry = _build_registry(ctx, run)

        messages: list[dict] = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_request},
        ]

        summary = ""
        for _ in range(MAX_STEPS):
            response = self.llm.chat(messages, tools=registry.schemas())
            message = response.choices[0].message
            messages.append(_message_to_dict(message))

            tool_calls = getattr(message, "tool_calls", None)
            if not tool_calls:
                summary = message.content or ""
                break

            for call in tool_calls:
                name = call.function.name
                try:
                    args = json.loads(call.function.arguments or "{}")
                except json.JSONDecodeError as exc:
                    result: Any = {"error": f"invalid tool arguments JSON: {exc}"}
                else:
                    try:
                        result = registry.execute(name, args)
                    except Exception as exc:
                        result = {"error": f"{type(exc).__name__}: {exc}"}
                run.log_step(name, args, result)
                messages.append(
                    {"role": "tool", "tool_call_id": call.id, "content": json.dumps(result, default=str)}
                )
        else:
            summary = "Reached the step limit before the model produced a final answer."
            ctx.warnings.append("Coordinator hit MAX_STEPS without a final natural-language answer.")

        panel_path = run.run_dir / "panel.parquet"
        if ctx.cross_sectional and panel_path.exists():
            reproduce_data_path: str | None = str(panel_path)
        elif ctx.data_path:
            reproduce_data_path = str(ctx.data_path)
        else:
            reproduce_data_path = None

        config = {
            "hypothesis": user_request,
            "model": self.model,
            "data_path": reproduce_data_path,
            "cache": ctx.cache_meta,
            "universe": ctx.universe.to_dict() if ctx.universe else None,
        }
        run.save_config(config)

        metrics = ctx.last_metrics or {}
        if ctx.data_path:
            data_hash = f"sha256:{file_sha256(ctx.data_path)}"
        elif panel_path.exists():
            data_hash = f"sha256:{file_sha256(panel_path)}"
        else:
            data_hash = "sha256:none"
        code_path = run.run_dir / "signal.py"
        code_hash = f"sha256:{file_sha256(code_path)}" if code_path.exists() else "sha256:none"

        if ctx.cross_sectional:
            note = build_cross_sectional_research_note(
                run.run_id,
                config,
                metrics,
                data_hash,
                ctx.warnings,
                summary,
                ctx.data_quality.to_dict() if ctx.data_quality else None,
            )
        else:
            note = build_research_note(run.run_id, config, metrics, data_hash, ctx.warnings, summary)
        run.save_text("research_note.md", note)
        run.save_json("conversation.json", messages)
        run.finalize(
            data_hash=data_hash,
            code_hash=code_hash,
            warnings=ctx.warnings,
            model=self.model,
            conversation_log="conversation.json",
            summary=summary,
            metrics=metrics,
        )

        return RunResult(
            run_id=run.run_id,
            run_dir=run.run_dir,
            metrics=metrics,
            warnings=ctx.warnings,
            summary=summary,
        )
