import difflib
import json
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from quantbench.agent.llm import LLMClient
from quantbench.agent.prompts import SYSTEM_PROMPT
from quantbench.api import run_reader
from quantbench.artifact.store import ArtifactStore
from quantbench.config import DEFAULT_COST_BPS, DEFAULT_MODEL, MAX_STEPS, RUNS_DIR
from quantbench.config import SKILL_DOCS_DIR as DEFAULT_SKILL_DOCS_DIR
from quantbench.data.cache import file_sha256
from quantbench.data.exchange import SYNTHETIC_FALLBACK_SOURCE, fetch_ohlcv
from quantbench.data.universe import UniverseDefinition, build_universe
from quantbench.data.warehouse import fetch_universe_ohlcv
from quantbench.engine.cross_sectional_backtest import run_cross_sectional_backtest
from quantbench.engine.metrics import sanity_check_metrics
from quantbench.engine.vectorized_backtest import run_vectorized_backtest
from quantbench.review import ReviewReport, run_review
from quantbench.factors.parametrize import apply_overrides
from quantbench.factors.store import FactorStore
from quantbench.library.aggregate import summarize as summarize_library
from quantbench.library.fork import build_fork_config
from quantbench.library.index import ExperimentIndex
from quantbench.skilldocs.inject import build_augmented_system_prompt
from quantbench.skilldocs.registry import SkillRegistryDocs
from quantbench.skills.codeexec import load_signal_function, run_signal_code
from quantbench.skills.data_quality import DataQualityReport, validate_universe_data
from quantbench.skills.plot import save_drawdown_plot, save_equity_curve_plot, save_group_returns_plot, save_ic_plot
from quantbench.skills.registry import Skill, SkillRegistry
from quantbench.skills.report import build_cross_sectional_research_note, build_research_note


@dataclass
class RunResult:
    run_id: str
    run_dir: Path
    metrics: dict[str, float]
    warnings: list[str]
    summary: str


FETCH_OHLCV_PARAMS = {
    "type": "object",
    "properties": {
        "symbol": {"type": "string", "description": "e.g. BTC/USDT for crypto, AAPL/MSFT/SPY for US equities"},
        "timeframe": {"type": "string", "description": "e.g. 4h for crypto, 1d for equities"},
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
    },
    "required": ["symbol", "timeframe", "start", "end"],
}

SIGNAL_FILE_HEADER = '''"""QuantBench Phase 0 signal - generated by the Coordinator agent.

Runnable standalone: `python signal.py <data.parquet> [--output out.csv]`
"""
import numpy as np
import pandas as pd


'''

SIGNAL_FILE_HARNESS = '''

if __name__ == "__main__":
    import argparse
    import os
    import sys
    from contextlib import contextmanager

    sys.dont_write_bytecode = True
    parser = argparse.ArgumentParser()
    parser.add_argument("data_path")
    parser.add_argument("--output")
    args = parser.parse_args()

    @contextmanager
    def _suppress_native_stderr():
        stderr_fd = 2
        saved_fd = os.dup(stderr_fd)
        try:
            with open(os.devnull, "w") as devnull:
                os.dup2(devnull.fileno(), stderr_fd)
                yield
        finally:
            os.dup2(saved_fd, stderr_fd)
            os.close(saved_fd)

    with _suppress_native_stderr():
        _df = pd.read_parquet(args.data_path)

    if "symbol" in _df.columns:
        # Multi-symbol panel (Phase 1 cross-sectional runs). compute() must be
        # applied per symbol, in the exact same shape run_cross_sectional_backtest
        # uses internally - never across the mixed long table directly, or the
        # reproduced numbers will silently diverge from the real backtest.
        _frames = []
        for _symbol, _symbol_df in _df.groupby("symbol", sort=False):
            _symbol_df = _symbol_df.sort_values("timestamp").reset_index(drop=True)
            _out_symbol = _symbol_df[["timestamp"]].copy()
            _out_symbol["symbol"] = _symbol
            _out_symbol["signal"] = compute(_symbol_df)
            _frames.append(_out_symbol)
        _out = pd.concat(_frames, ignore_index=True).sort_values(["timestamp", "symbol"])
    else:
        _out = _df[["timestamp"]].copy()
        _out["signal"] = compute(_df)

    _csv = _out.to_csv(index=False)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as handle:
            handle.write(_csv)
    else:
        print(_csv)
'''

RUN_SIGNAL_BACKTEST_PARAMS = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Python source defining `def compute(df: pd.DataFrame) -> pd.Series`. "
                "Only `pd` and `np` are available, no imports. Must be causal: only use "
                "rows up to and including the current index, never future rows."
            ),
        },
        "cost_bps": {
            "type": "number",
            "description": "Round-trip trading cost in basis points. Default 5.",
        },
    },
    "required": ["code"],
}

BUILD_UNIVERSE_PARAMS = {
    "type": "object",
    "properties": {
        "universe_name": {
            "type": "string",
            "description": "Universe name, e.g. sp500 or top_usdt_perpetual for crypto perpetual swaps.",
        },
        "as_of_date": {"type": "string", "description": "YYYY-MM-DD date for the universe definition."},
        "point_in_time": {
            "type": "boolean",
            "description": "Phase 1 v1 only supports false. True raises an explicit not-implemented error.",
        },
        "limit": {
            "type": "integer",
            "description": (
                "Optional: truncate to the first N tickers (alphabetically) instead of the "
                "full ~500. Use this whenever the user asks for a quick/small/cheap test - "
                "fetching all 500 symbols sequentially is slow and not needed to sanity-check "
                "a factor idea. The universe is clearly marked as a non-representative sample."
            ),
        },
    },
    "required": ["universe_name", "as_of_date"],
}

RUN_CROSS_SECTIONAL_BACKTEST_PARAMS = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Python source defining `def compute(df: pd.DataFrame) -> pd.Series`. "
                "The function is called once per symbol and must be causal."
            ),
        },
        "start": {"type": "string", "description": "YYYY-MM-DD"},
        "end": {"type": "string", "description": "YYYY-MM-DD"},
        "timeframe": {"type": "string", "description": "Use 1d for US equities."},
        "n_groups": {"type": "integer", "description": "Number of factor groups, default 10."},
        "cost_bps": {"type": "number", "description": "Round-trip trading cost in basis points. Default 5."},
    },
    "required": ["code", "start", "end"],
}


CRYPTO_PERPETUAL_FUNDING_WARNING = (
    "Crypto perpetual backtests do not model funding rate carry cost. Long-short "
    "positions held across funding intervals may have systematically biased PnL "
    "that this backtest does not capture."
)


class _RunContext:
    """Mutable state threaded through one Coordinator.run() call."""

    def __init__(self) -> None:
        self.data_path: Path | None = None
        self.data_df = None
        self.cache_meta: dict[str, Any] | None = None
        self.last_metrics: dict[str, float] | None = None
        self.signal_code: str | None = None
        self.universe: UniverseDefinition | None = None
        self.panel_df = None
        self.data_quality: DataQualityReport | None = None
        self.cross_sectional = False
        self.warnings: list[str] = []
        self.fetch_params: dict[str, str] | None = None
        self.review_report: ReviewReport | None = None
        self.injected_skills: list[str] = []


def _build_registry(ctx: _RunContext, run) -> SkillRegistry:
    registry = SkillRegistry()

    def _fetch_ohlcv(symbol: str, timeframe: str, start: str, end: str) -> dict:
        data_path, data_df, cache_meta = fetch_ohlcv(symbol, timeframe, start, end)
        ctx.data_path, ctx.data_df, ctx.cache_meta = data_path, data_df, cache_meta
        ctx.fetch_params = {"symbol": symbol, "timeframe": timeframe, "start": start, "end": end}

        if cache_meta.get("source") == SYNTHETIC_FALLBACK_SOURCE:
            ctx.warnings.append(
                "DATA IS SYNTHETIC, NOT REAL MARKET DATA. Real data fetch failed "
                f"({cache_meta.get('fallback_reason')}); every downstream metric is "
                "meaningless for real trading decisions."
            )
        elif cache_meta.get("source") == "unknown_legacy_cache":
            ctx.warnings.append(
                "Cached data has no provenance metadata (cached before source tracking "
                "existed). Delete data_cache/ and re-run to confirm real vs synthetic."
            )

        return {
            "rows": len(data_df),
            "start": str(data_df["timestamp"].iloc[0]) if len(data_df) else None,
            "end": str(data_df["timestamp"].iloc[-1]) if len(data_df) else None,
            "source": cache_meta.get("source"),
            "cache_hit": cache_meta.get("cache_hit"),
        }

    def _run_signal_backtest(code: str, cost_bps: float = DEFAULT_COST_BPS) -> dict:
        if ctx.data_df is None:
            return {"error": "no market data loaded yet - call fetch_ohlcv first"}

        signal = run_signal_code(code, ctx.data_df)
        backtest = run_vectorized_backtest(ctx.data_df, signal, cost_bps=cost_bps)

        ctx.signal_code = code
        ctx.last_metrics = backtest.metrics
        run.save_code("signal.py", SIGNAL_FILE_HEADER + code + SIGNAL_FILE_HARNESS)
        run.save_json("backtest_result.json", backtest.to_json_dict())
        save_equity_curve_plot(backtest.equity_curve, run.run_dir / "equity_curve.png")
        save_drawdown_plot(backtest.drawdown, run.run_dir / "drawdown.png")

        new_warnings = _append_crypto_perpetual_warning(ctx) if _is_crypto_symbol(ctx.fetch_params) else []
        new_warnings.extend(sanity_check_metrics(backtest.metrics))
        benchmark_symbol = _benchmark_symbol_from_fetch_params(ctx.fetch_params)
        review_report = run_review(
            code=code,
            returns=backtest.returns,
            cost_bps=cost_bps,
            rerun_at_cost=lambda bps: run_vectorized_backtest(ctx.data_df, signal, cost_bps=bps).metrics,
            rerun_with_code=lambda candidate: _rerun_single_with_code(candidate, ctx.data_df, cost_bps),
            out_of_sample_data=ctx.data_df,
            run_on_data=lambda data: _rerun_single_with_code(code, data, cost_bps) or {},
            benchmark_returns=_fetch_benchmark_returns(ctx.fetch_params, ctx.data_df),
            benchmark_symbol=benchmark_symbol,
            turnover_annual=backtest.metrics.get("turnover_annual"),
        )
        ctx.review_report = review_report
        run.save_json("review_report.json", review_report.to_dict())
        review_warnings = _review_warning_messages(review_report)
        new_warnings.extend(review_warnings)
        ctx.warnings.extend(new_warnings)

        return {**backtest.metrics, "warnings": new_warnings, "review": review_report.to_dict()}

    def _build_universe(
        universe_name: str, as_of_date: str, point_in_time: bool = False, limit: int | None = None
    ) -> dict:
        universe = build_universe(universe_name, as_of_date, point_in_time=point_in_time, limit=limit)
        ctx.universe = universe
        run.save_text("universe.yaml", __import__("yaml").safe_dump(universe.to_dict(), sort_keys=False, allow_unicode=True))
        ctx.warnings.append(universe.survivorship_bias_note)
        return {
            "name": universe.name,
            "as_of_date": universe.as_of_date,
            "symbols": len(universe.symbols),
            "point_in_time": universe.point_in_time,
            "sample_limit": universe.sample_limit,
            "asset_class": universe.asset_class,
            "survivorship_bias_note": universe.survivorship_bias_note,
            "source": universe.source,
        }

    def _run_cross_sectional_backtest(
        code: str,
        start: str,
        end: str,
        timeframe: str = "1d",
        n_groups: int = 10,
        cost_bps: float = DEFAULT_COST_BPS,
    ) -> dict:
        if ctx.universe is None:
            return {"error": "no universe loaded yet - call build_universe first"}

        panel, cache_meta = fetch_universe_ohlcv(ctx.universe, timeframe, start, end)
        ctx.panel_df = panel
        ctx.cache_meta = cache_meta
        ctx.data_quality = validate_universe_data(panel, ctx.universe, end=end)
        ctx.cross_sectional = True

        if ctx.data_quality.symbols_missing_entirely:
            ctx.warnings.append(
                f"{len(ctx.data_quality.symbols_missing_entirely)} universe symbols have no data and were excluded."
            )
        if ctx.data_quality.symbols_with_gaps:
            ctx.warnings.append(f"{len(ctx.data_quality.symbols_with_gaps)} symbols have missing business-day gaps.")
        if ctx.data_quality.suspicious_price_jumps:
            ctx.warnings.append(
                f"{len(ctx.data_quality.suspicious_price_jumps)} symbols have >50% one-period price jumps."
            )

        compute = load_signal_function(code)
        backtest = run_cross_sectional_backtest(
            panel,
            compute,
            n_groups=n_groups,
            cost_bps=cost_bps,
        )

        ctx.signal_code = code
        ctx.last_metrics = backtest.metrics
        panel_path = run.run_dir / "panel.parquet"
        panel.to_parquet(panel_path, index=False)
        run.save_code("signal.py", SIGNAL_FILE_HEADER + code + SIGNAL_FILE_HARNESS)
        # Same filename as the single-symbol path (not "cross_sectional_backtest_result.json" -
        # that name drifted from the single-symbol path's and matches nothing else in the
        # codebase or README's documented artifact layout; readers like ChartsPanel and
        # library/compare.py's compute_returns_correlation() look for one canonical name).
        run.save_json("backtest_result.json", backtest.to_json_dict())
        run.save_json("data_quality_report.json", ctx.data_quality.to_dict())
        save_equity_curve_plot(backtest.equity_curve, run.run_dir / "equity_curve.png")
        save_drawdown_plot(backtest.drawdown, run.run_dir / "drawdown.png")
        save_group_returns_plot(backtest.group_returns, run.run_dir / "group_returns.png")
        save_ic_plot(backtest.ic_series, run.run_dir / "rank_ic.png")

        new_warnings = _append_crypto_perpetual_warning(ctx) if _is_crypto_universe(ctx.universe) else []
        new_warnings.extend(sanity_check_metrics(backtest.metrics))
        benchmark_symbol = _benchmark_symbol_for_asset(ctx.universe.asset_class)
        review_report = run_review(
            code=code,
            returns=backtest.returns,
            cost_bps=cost_bps,
            rerun_at_cost=lambda bps: run_cross_sectional_backtest(panel, compute, n_groups=n_groups, cost_bps=bps).metrics,
            rerun_with_code=lambda candidate: _rerun_cross_with_code(candidate, panel, n_groups, cost_bps),
            out_of_sample_data=panel,
            run_on_data=lambda data: _rerun_cross_with_code(code, data, n_groups, cost_bps) or {},
            benchmark_returns=_fetch_benchmark_returns(
                {"symbol": benchmark_symbol, "timeframe": timeframe, "start": start, "end": end}, None
            ),
            benchmark_symbol=benchmark_symbol,
            factor_panel=backtest.factor_panel,
            n_groups=n_groups,
            turnover_annual=backtest.metrics.get("turnover_annual"),
        )
        ctx.review_report = review_report
        run.save_json("review_report.json", review_report.to_dict())
        review_warnings = _review_warning_messages(review_report)
        new_warnings.extend(review_warnings)
        ctx.warnings.extend(new_warnings)

        return {
            **backtest.metrics,
            "data_quality": ctx.data_quality.to_dict(),
            "cache": cache_meta,
            "warnings": new_warnings,
            "review": review_report.to_dict(),
        }

    registry.register(
        Skill("fetch_ohlcv", "Fetch and cache OHLCV market data.", FETCH_OHLCV_PARAMS, _fetch_ohlcv)
    )
    registry.register(
        Skill(
            "run_signal_backtest",
            "Run signal code against the fetched data and backtest it.",
            RUN_SIGNAL_BACKTEST_PARAMS,
            _run_signal_backtest,
        )
    )
    registry.register(
        Skill("build_universe", "Build a named equity universe such as the current S&P 500.", BUILD_UNIVERSE_PARAMS, _build_universe)
    )
    registry.register(
        Skill(
            "run_cross_sectional_backtest",
            "Fetch a universe panel, run causal factor code per symbol, and backtest equal-weight factor groups.",
            RUN_CROSS_SECTIONAL_BACKTEST_PARAMS,
            _run_cross_sectional_backtest,
        )
    )
    return registry


def _build_fork_registry(ctx: _RunContext, run) -> SkillRegistry:
    registry = SkillRegistry()

    def _run_signal_backtest(code: str, cost_bps: float = DEFAULT_COST_BPS) -> dict:
        if ctx.data_df is None:
            return {"error": "fork data is unavailable - parent data_path could not be loaded"}

        signal = run_signal_code(code, ctx.data_df)
        backtest = run_vectorized_backtest(ctx.data_df, signal, cost_bps=cost_bps)

        ctx.signal_code = code
        ctx.last_metrics = backtest.metrics
        run.save_code("signal.py", SIGNAL_FILE_HEADER + code + SIGNAL_FILE_HARNESS)
        run.save_json("backtest_result.json", backtest.to_json_dict())
        save_equity_curve_plot(backtest.equity_curve, run.run_dir / "equity_curve.png")
        save_drawdown_plot(backtest.drawdown, run.run_dir / "drawdown.png")

        new_warnings = sanity_check_metrics(backtest.metrics)
        review_report = run_review(
            code=code,
            returns=backtest.returns,
            cost_bps=cost_bps,
            rerun_at_cost=lambda bps: run_vectorized_backtest(ctx.data_df, signal, cost_bps=bps).metrics,
            rerun_with_code=lambda candidate: _rerun_single_with_code(candidate, ctx.data_df, cost_bps),
            out_of_sample_data=ctx.data_df,
            run_on_data=lambda data: _rerun_single_with_code(code, data, cost_bps) or {},
            benchmark_returns=None,
            turnover_annual=backtest.metrics.get("turnover_annual"),
        )
        ctx.review_report = review_report
        run.save_json("review_report.json", review_report.to_dict())
        new_warnings.extend(_review_warning_messages(review_report))
        ctx.warnings.extend(new_warnings)
        return {**backtest.metrics, "warnings": new_warnings, "review": review_report.to_dict()}

    registry.register(
        Skill(
            "run_signal_backtest",
            "Run revised fork signal code against the fixed parent data. No data fetching or universe changes are available.",
            RUN_SIGNAL_BACKTEST_PARAMS,
            _run_signal_backtest,
        )
    )
    return registry


def _message_to_dict(message: Any) -> dict:
    entry: dict[str, Any] = {"role": getattr(message, "role", "assistant"), "content": getattr(message, "content", None)}
    tool_calls = getattr(message, "tool_calls", None)
    if tool_calls:
        entry["tool_calls"] = [
            {
                "id": call.id,
                "type": "function",
                "function": {"name": call.function.name, "arguments": call.function.arguments},
            }
            for call in tool_calls
        ]
    return entry


class Coordinator:
    def __init__(
        self,
        model: str | None = None,
        run_store: ArtifactStore | None = None,
        llm: LLMClient | None = None,
    ):
        self.model = model or DEFAULT_MODEL
        self.run_store = run_store or ArtifactStore(RUNS_DIR)
        self.llm = llm or LLMClient(self.model)

    def run(self, user_request: str, *, skill_names: list[str] | None = None) -> RunResult:
        run = self.run_store.create_run(user_request)
        return self.execute(run, user_request, skill_names=skill_names)

    def run_from_factor(
        self,
        factor_name: str,
        param_overrides: dict[str, str] | None,
        request: str,
        *,
        skill_names: list[str] | None = None,
        factor_store: FactorStore | None = None,
    ) -> RunResult:
        store = factor_store or FactorStore()
        factor = store.load_factor(factor_name)
        code = apply_overrides(factor.code, param_overrides or {})
        limitations = "\n".join(
            f"- {finding.get('severity')} [{finding.get('check')}]: {finding.get('message')}"
            for finding in factor.source_findings
        ) or "- none recorded"
        seed_request = (
            f"Use factor-library entry `{factor.name}` as the starting point for this run.\n"
            f"Source run: {factor.source_run_id}; source verdict: {factor.source_verdict}.\n"
            f"Known limitations from reviewer findings:\n{limitations}\n\n"
            "Starting signal code after requested parameter overrides:\n"
            f"```python\n{code}\n```\n\n"
            "Run the normal QuantBench workflow for this new request. You may revise the code if the new data or scenario requires it.\n"
            f"User request: {request}"
        )
        run = self.run_store.create_run(f"Factor {factor_name}: {request}")
        return self.execute(
            run,
            request,
            skill_names=skill_names,
            derived_from_factor=factor_name,
            prompt_override=seed_request,
        )

    def run_fork(self, parent_run_id: str, modification_request: str) -> RunResult:
        run = self.run_store.create_run(f"Fork {parent_run_id}: {modification_request}")
        return self.execute_fork(run, parent_run_id, modification_request)

    def execute(
        self,
        run,
        user_request: str,
        on_event: Callable[[dict[str, Any]], None] | None = None,
        parent_run_id: str | None = None,
        skill_names: list[str] | None = None,
        derived_from_factor: str | None = None,
        prompt_override: str | None = None,
    ) -> RunResult:
        """Drive the tool-use loop for an already-created Run.

        Split out from `run()` so callers that need the run_id before execution
        finishes (e.g. the web API, which returns run_id immediately and runs
        the loop in a background thread) can call `run_store.create_run(...)`
        themselves first, then hand the Run object here.

        `on_event`, if given, is called synchronously with a small dict at each
        step (tool call start/end, final answer) - purely an observation hook
        for live progress streaming (see quantbench/api). It never influences
        the loop's own logic or control flow.

        `prompt_override`, if given, replaces `user_request` only as the
        content of the first LLM message (e.g. run_from_factor's seed prompt,
        which embeds reference code and reviewer findings). `user_request`
        itself stays the clean human request text everywhere else - it's what
        `config.yaml`'s `hypothesis` records, what the experiment library's
        factor_family classifier reads, and what Skill matching runs against.
        Matching Skills against a prompt stuffed with factor code and finding
        text would risk spurious keyword hits unrelated to the user's actual
        intent, and "hypothesis" showing a code blob instead of the request
        would make the experiment library unreadable.
        """

        def emit(event: dict[str, Any]) -> None:
            if on_event is not None:
                on_event(event)

        if _is_library_question(user_request):
            return self._execute_library_question(run, user_request, emit)

        ctx = _RunContext()
        registry = _build_registry(ctx, run)
        matched_skills = _select_skill_docs(user_request, skill_names)
        ctx.injected_skills = [skill.name for skill in matched_skills]
        system_prompt = build_augmented_system_prompt(SYSTEM_PROMPT, matched_skills)

        messages: list[dict] = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt_override or user_request},
        ]

        emit({"type": "start"})
        summary = ""
        for _ in range(MAX_STEPS):
            response = self.llm.chat(messages, tools=registry.schemas())
            message = response.choices[0].message
            messages.append(_message_to_dict(message))

            tool_calls = getattr(message, "tool_calls", None)
            if not tool_calls:
                summary = message.content or ""
                emit({"type": "final", "summary": summary})
                break

            for call in tool_calls:
                name = call.function.name
                try:
                    args = json.loads(call.function.arguments or "{}")
                except json.JSONDecodeError as exc:
                    result: Any = {"error": f"invalid tool arguments JSON: {exc}"}
                else:
                    emit({"type": "tool_start", "tool": name, "args": args})
                    try:
                        result = registry.execute(name, args)
                    except Exception as exc:
                        result = {"error": f"{type(exc).__name__}: {exc}"}
                run.log_step(name, args, result)
                emit({"type": "tool_end", "tool": name, "result": result})
                messages.append(
                    {"role": "tool", "tool_call_id": call.id, "content": json.dumps(result, default=str)}
                )
        else:
            summary = "Reached the step limit before the model produced a final answer."
            ctx.warnings.append("Coordinator hit MAX_STEPS without a final natural-language answer.")
            emit({"type": "final", "summary": summary})

        panel_path = run.run_dir / "panel.parquet"
        if ctx.cross_sectional and panel_path.exists():
            reproduce_data_path: str | None = str(panel_path)
        elif ctx.data_path:
            reproduce_data_path = str(ctx.data_path)
        else:
            reproduce_data_path = None

        config = {
            "hypothesis": user_request,
            "model": self.model,
            "data_path": reproduce_data_path,
            "cache": ctx.cache_meta,
            "universe": ctx.universe.to_dict() if ctx.universe else None,
            "parent_run_id": parent_run_id,
            "derived_from_factor": derived_from_factor,
            "injected_skills": ctx.injected_skills,
        }
        run.save_config(config)

        metrics = ctx.last_metrics or {}
        if ctx.data_path:
            data_hash = f"sha256:{file_sha256(ctx.data_path)}"
        elif panel_path.exists():
            data_hash = f"sha256:{file_sha256(panel_path)}"
        else:
            data_hash = "sha256:none"
        code_path = run.run_dir / "signal.py"
        code_hash = f"sha256:{file_sha256(code_path)}" if code_path.exists() else "sha256:none"

        if ctx.cross_sectional:
            note = build_cross_sectional_research_note(
                run.run_id,
                config,
                metrics,
                data_hash,
                ctx.warnings,
                summary,
                ctx.data_quality.to_dict() if ctx.data_quality else None,
                ctx.review_report.to_markdown() if ctx.review_report else "",
            )
        else:
            note = build_research_note(
                run.run_id,
                config,
                metrics,
                data_hash,
                ctx.warnings,
                summary,
                ctx.review_report.to_markdown() if ctx.review_report else "",
            )
        run.save_text("research_note.md", note)
        run.save_json("conversation.json", messages)
        run.finalize(
            data_hash=data_hash,
            code_hash=code_hash,
            warnings=ctx.warnings,
            model=self.model,
            conversation_log="conversation.json",
            summary=summary,
            metrics=metrics,
            review=ctx.review_report.to_dict() if ctx.review_report else None,
            parent_run_id=parent_run_id,
            injected_skills=ctx.injected_skills,
        )

        return RunResult(
            run_id=run.run_id,
            run_dir=run.run_dir,
            metrics=metrics,
            warnings=ctx.warnings,
            summary=summary,
        )

    def _execute_library_question(
        self,
        run,
        user_request: str,
        emit: Callable[[dict[str, Any]], None],
    ) -> RunResult:
        rows = summarize_library(ExperimentIndex.build())
        aggregate_json = json.dumps(rows, ensure_ascii=False, indent=2, sort_keys=True)
        messages: list[dict] = [
            {
                "role": "system",
                "content": (
                    "You answer QuantBench experiment-library questions. Any number, ranking, or comparison in your "
                    "answer must come only from the injected aggregate table. Do not estimate or recount runs yourself. "
                    "If a group has sample_warning=true, state that the sample is too small for a firm conclusion."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"User question: {user_request}\n\n"
                    "Deterministic aggregate table from quantbench.library.aggregate.summarize():\n"
                    f"{aggregate_json}"
                ),
            },
        ]
        emit({"type": "start", "mode": "library_question"})
        response = self.llm.chat(messages, tools=[])
        message = response.choices[0].message
        summary = message.content or ""
        emit({"type": "final", "summary": summary})

        config = {"hypothesis": user_request, "model": self.model, "library_question": True}
        run.save_config(config)
        run.save_json("library_summary.json", rows)
        run.save_json("conversation.json", messages + [_message_to_dict(message)])
        note = build_research_note(
            run.run_id,
            config,
            {},
            "sha256:none",
            [],
            summary,
            "(实验库问答模式：未运行 Reviewer 审查)",
        )
        run.save_text("research_note.md", note)
        run.finalize(
            data_hash="sha256:none",
            code_hash="sha256:none",
            warnings=[],
            model=self.model,
            conversation_log="conversation.json",
            summary=summary,
            metrics={},
            review=None,
        )
        return RunResult(run_id=run.run_id, run_dir=run.run_dir, metrics={}, warnings=[], summary=summary)

    def execute_fork(
        self,
        run,
        parent_run_id: str,
        modification_request: str,
        on_event: Callable[[dict[str, Any]], None] | None = None,
    ) -> RunResult:
        seed_config = build_fork_config(parent_run_id, modification_request)

        # v1 fork only supports single-symbol parents. A cross-sectional parent's
        # data_path points at panel.parquet (a multi-symbol panel); feeding that
        # into the single-symbol vectorized backtest below would silently produce
        # garbage. Refuse explicitly rather than run the wrong math.
        if seed_config.get("universe"):
            raise ValueError(
                f"Fork not supported for cross-sectional run {parent_run_id}: "
                "forking multi-symbol (universe) experiments is not implemented yet. "
                "Fork a single-symbol run instead."
            )

        data_path = Path(seed_config["data_path"]) if seed_config.get("data_path") else None

        ctx = _RunContext()
        ctx.cache_meta = seed_config.get("cache")
        if data_path and data_path.exists():
            fixed_df = pd.read_parquet(data_path)
            ctx.data_path = data_path
            ctx.data_df = fixed_df
        else:
            ctx.warnings.append("Fork parent data_path is missing; backtest cannot run until fixed data is available.")

        registry = _build_fork_registry(ctx, run)

        def emit(event: dict[str, Any]) -> None:
            if on_event is not None:
                on_event(event)

        fork_prompt = (
            f"This is a fork of {parent_run_id}. The data and universe are fixed and already loaded. "
            "Only rewrite the compute() signal according to the user's modification. "
            "Do not fetch data or change the universe.\n\n"
            f"Modification request: {modification_request}\n\n"
            "Parent signal code:\n"
            f"{seed_config.get('parent_signal_code', '')}"
        )
        messages: list[dict] = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": fork_prompt},
        ]

        emit({"type": "start", "parent_run_id": parent_run_id})
        summary = ""
        for _ in range(MAX_STEPS):
            response = self.llm.chat(messages, tools=registry.schemas())
            message = response.choices[0].message
            messages.append(_message_to_dict(message))

            tool_calls = getattr(message, "tool_calls", None)
            if not tool_calls:
                summary = message.content or ""
                emit({"type": "final", "summary": summary})
                break

            for call in tool_calls:
                name = call.function.name
                try:
                    args = json.loads(call.function.arguments or "{}")
                except json.JSONDecodeError as exc:
                    result: Any = {"error": f"invalid tool arguments JSON: {exc}"}
                else:
                    emit({"type": "tool_start", "tool": name, "args": args})
                    try:
                        result = registry.execute(name, args)
                    except Exception as exc:
                        result = {"error": f"{type(exc).__name__}: {exc}"}
                run.log_step(name, args, result)
                emit({"type": "tool_end", "tool": name, "result": result})
                messages.append({"role": "tool", "tool_call_id": call.id, "content": json.dumps(result, default=str)})
        else:
            summary = "Reached the step limit before the model produced a final answer."
            ctx.warnings.append("Coordinator hit MAX_STEPS without a final natural-language answer.")
            emit({"type": "final", "summary": summary})

        metrics = ctx.last_metrics or {}
        config = {
            **{key: value for key, value in seed_config.items() if key != "parent_signal_code"},
            "hypothesis": f"{seed_config.get('hypothesis', '')} | fork: {modification_request}",
            "model": self.model,
        }
        run.save_config(config)

        if data_path and data_path.exists():
            data_hash = f"sha256:{file_sha256(data_path)}"
        else:
            data_hash = seed_config.get("parent_data_hash") or "sha256:none"
        parent_hash = seed_config.get("parent_data_hash")
        if parent_hash and data_hash != parent_hash:
            ctx.warnings.append("Fork data drift: child data_hash differs from parent data_hash.")

        code_path = run.run_dir / "signal.py"
        code_hash = f"sha256:{file_sha256(code_path)}" if code_path.exists() else "sha256:none"
        note = build_research_note(
            run.run_id,
            config,
            metrics,
            data_hash,
            ctx.warnings,
            summary,
            ctx.review_report.to_markdown() if ctx.review_report else "",
            _fork_lineage_markdown(parent_run_id, seed_config.get("parent_signal_code", ""), code_path, metrics),
        )
        run.save_text("research_note.md", note)
        run.save_json("conversation.json", messages)
        run.finalize(
            data_hash=data_hash,
            code_hash=code_hash,
            warnings=ctx.warnings,
            model=self.model,
            conversation_log="conversation.json",
            summary=summary,
            metrics=metrics,
            review=ctx.review_report.to_dict() if ctx.review_report else None,
            parent_run_id=parent_run_id,
        )
        return RunResult(run_id=run.run_id, run_dir=run.run_dir, metrics=metrics, warnings=ctx.warnings, summary=summary)


def _select_skill_docs(user_request: str, skill_names: list[str] | None) -> list:
    registry = SkillRegistryDocs(DEFAULT_SKILL_DOCS_DIR)
    selected = []
    seen = set()
    for name in skill_names or []:
        doc = registry.get(name)
        selected.append(doc)
        seen.add(doc.name)
    for doc in registry.match(user_request):
        if doc.name not in seen:
            selected.append(doc)
            seen.add(doc.name)
    return selected


def _rerun_single_with_code(code: str, data_df, cost_bps: float) -> dict[str, float] | None:
    try:
        signal = run_signal_code(code, data_df)
        return run_vectorized_backtest(data_df, signal, cost_bps=cost_bps).metrics
    except Exception:
        return None


def _rerun_cross_with_code(code: str, panel, n_groups: int, cost_bps: float) -> dict[str, float] | None:
    try:
        compute = load_signal_function(code)
        return run_cross_sectional_backtest(panel, compute, n_groups=n_groups, cost_bps=cost_bps).metrics
    except Exception:
        return None


def _fetch_benchmark_returns(fetch_params: dict[str, str] | None, current_df) -> Any:
    if not fetch_params:
        return None
    symbol = fetch_params.get("symbol", "")
    benchmark = "BTC/USDT" if "/" in symbol else "SPY"
    try:
        if current_df is not None and symbol == benchmark:
            benchmark_df = current_df
        else:
            _, benchmark_df, _ = fetch_ohlcv(
                benchmark,
                fetch_params.get("timeframe", "1d"),
                fetch_params.get("start", ""),
                fetch_params.get("end", ""),
            )
        returns = benchmark_df["close"].pct_change()
        returns.index = pd.to_datetime(benchmark_df["timestamp"], utc=True)
        return returns
    except Exception:
        return None


def _benchmark_symbol_from_fetch_params(fetch_params: dict[str, str] | None) -> str | None:
    if not fetch_params:
        return None
    return "BTC/USDT" if "/" in fetch_params.get("symbol", "") else "SPY"


def _benchmark_symbol_for_asset(asset_class: str) -> str:
    return "BTC/USDT" if asset_class == "crypto" else "SPY"


def _is_crypto_symbol(fetch_params: dict[str, str] | None) -> bool:
    return bool(fetch_params and "/" in fetch_params.get("symbol", ""))


def _is_crypto_universe(universe: UniverseDefinition | None) -> bool:
    return bool(universe and universe.asset_class == "crypto")


def _append_crypto_perpetual_warning(ctx: _RunContext) -> list[str]:
    if CRYPTO_PERPETUAL_FUNDING_WARNING not in ctx.warnings:
        ctx.warnings.append(CRYPTO_PERPETUAL_FUNDING_WARNING)
        return [CRYPTO_PERPETUAL_FUNDING_WARNING]
    return []


def _is_library_question(user_request: str) -> bool:
    """Detect a cross-run experiment-library question (vs. a request to run a
    new backtest). Deliberately conservative: routing a real backtest request
    into library-question mode would silently skip the backtest, so we only
    match on phrases that clearly refer to the *existing* body of experiments,
    not on common single words like "run"/"best" that appear in ordinary
    backtest requests (e.g. "run a backtest to find the best momentum factor").
    """
    text = user_request.lower()
    history_markers = (
        "做过的所有",
        "所有实验",
        "实验库",
        "实验历史",
        "历史实验",
        "过往实验",
        "experiment library",
        "past experiments",
        "all experiments",
        "across runs",
        "my experiments",
        "my runs",
    )
    return any(marker in text for marker in history_markers)


def _review_warning_messages(review_report: ReviewReport) -> list[str]:
    messages: list[str] = []
    if review_report.verdict in {"WEAK", "REJECTED"}:
        messages.append(f"Reviewer verdict: {review_report.verdict} - {review_report.verdict_reason}")
    for finding in review_report.findings:
        if finding.severity in {"critical", "warning"}:
            messages.append(f"Reviewer {finding.severity.upper()} [{finding.check}]: {finding.message}")
    return messages


def _fork_lineage_markdown(parent_run_id: str, parent_signal_code: str, child_signal_path: Path, child_metrics: dict[str, float]) -> str:
    parent_manifest = run_reader.read_manifest(parent_run_id) or {}
    parent_metrics = parent_manifest.get("metrics") or {}
    delta_lines = []
    for key in ("sharpe", "annual_return", "max_drawdown", "turnover_annual", "ic_mean"):
        before = parent_metrics.get(key)
        after = child_metrics.get(key)
        if before is None or after is None:
            continue
        delta_lines.append(f"- {key}: {before} → {after} (delta {after - before:+.4g})")

    child_signal = child_signal_path.read_text(encoding="utf-8") if child_signal_path.exists() else ""
    diff = "".join(
        difflib.unified_diff(
            parent_signal_code.splitlines(keepends=True),
            child_signal.splitlines(keepends=True),
            fromfile=f"{parent_run_id}/signal.py",
            tofile="child/signal.py",
        )
    )
    diff_block = f"\n```diff\n{diff[:4000]}\n```\n" if diff else "\n(信号代码无差异或不可用)\n"
    return f"""## 谱系
- 父 run: `{parent_run_id}`

### 指标变化
{chr(10).join(delta_lines) if delta_lines else "- 指标 delta 不可用"}

### 信号 diff
{diff_block}
"""
